### ISSUE TITLE
Method to listen to sockets

### ISSUE THREAD

**Issue by Frostie2** [Exaphis/HackQ-Trivia#140]
Hello!

I like your bot, its so amazing! But I'm interested in one thing:
How did you find out that you have to add the bearer and the x-hq-client argument as header to the websocket connection? I tried to use a SOCKS proxy to listen to the socket and even to find out what the client is sending when tapping an answer or whatever, but it shows nothing.

Is there anyone who can tell me how to find that out? Or @Exaphis? Thank you so much!!!

Regards, Daniel

**Comment by Exaphis** [comment]
I initially found it out through mikealmond's hq-trivia-assistant, it has since been taken down. I inspect my traffic through Fiddler and an older Android phone, since by default after Android N will ignore user-installed root certificates for HTTPS certificate validation. You should be able to inspect your HTTPS traffic for any iPhone or for anything earlier than Android N.

**Comment by Frostie2** [comment]
Thank you so much!
