### ISSUE TITLE
Bearer Token

### ISSUE THREAD

**Issue by zoegodterry** [Exaphis/HackQ-Trivia#163]
Anyone have working US and UK bearer tokens?

**Comment by pk372** [comment]
https://github.com/Mandruyd/HQ-Token    Use this program to get bearer token simply 
But this script giving result every time

**Comment by mhornblower** [comment]
Something might have changed with the way the tokens are processed on the HQ end of things.  I have double and triple checked my token and user ID (retrieved via MITM just today and they have not changed since) and still get the authentication error.   Interestingly,  its only when HQ is actually live - when there is no game in progress it seems to talk to the HQ servers just fine and simply reports that there is no game and returns the correct time that the next one is scheduled  

Anyone still digging away at this?

**Comment by Exaphis** [comment]
Try out the new version, let me know if there still is a problem.
